import { createSlice } from "@reduxjs/toolkit";
import img1 from "../assets/img1.png";
import img2 from "../assets/img2.png";
import img3 from "../assets/img3.png";
import img4 from "../assets/img4.jpg";
import img5 from "../assets/img5.png";
import img6 from "../assets/img6.png";
import img7 from "../assets/img7.jpg";
import img8 from "../assets/img8.jpg";
import img9 from "../assets/img9.jpg";
import img10 from "../assets/img10.jpg";
import img11 from "../assets/img11.png";
import img12 from "../assets/img12.png";
import post1 from "../assets/postImg1.png";
import post2 from "../assets/postImg2.png";
import post3 from "../assets/postImg3.png";

const initialState = {
  products: [],
  allFoodCourses: [
    {
      id: 1,
      imgUrl: img1,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Zibiah Surya",
      Duration: "05 hr 15 mins",
      Lectures: 10,
      Level: "Beginner",
      Language: "English",
      Certificate: "Yes",
      Enrolled: 300,
    },
    {
      id: 2,
      imgUrl: img2,
      title: "Healthy salad",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "",
      qty: 1,
      Instructor: "Ravi Kumar",
      Duration: "03 hr 45 mins",
      Lectures: 8,
      Level: "Intermediate",
      Language: "English",
      Certificate: "No",
      Enrolled: 150,
    },
    {
      id: 3,
      imgUrl: img3,
      title: "Soup and curry",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Certified Course",
      qty: 1,
      Instructor: "Meera Singh",
      Duration: "06 hr 20 mins",
      Lectures: 12,
      Level: "Advanced",
      Language: "Hindi",
      Certificate: "Yes",
      Enrolled: 420,
    },
    {
      id: 4,
      imgUrl: img4,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Anjali Rao",
      Duration: "04 hr 05 mins",
      Lectures: 9,
      Level: "Beginner",
      Language: "English",
      Certificate: "Yes",
      Enrolled: 210,
    },
    {
      id: 5,
      imgUrl: img5,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Rahul Sharma",
      Duration: "02 hr 50 mins",
      Lectures: 8,
      Level: "Intermediate",
      Language: "English",
      Certificate: "Yes",
      Enrolled: 150,
    },
    {
      id: 6,
      imgUrl: img6,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Sonia Verma",
      Duration: "05 hr 40 mins",
      Lectures: 11,
      Level: "Beginner",
      Language: "English",
      Certificate: "Yes",
      Enrolled: 330,
    },
    {
      id: 7,
      imgUrl: img7,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Amit Patel",
      Duration: "01 hr 30 mins",
      Lectures: 4,
      Level: "Beginner",
      Language: "English",
      Certificate: "No",
      Enrolled: 95,
    },
    {
      id: 8,
      imgUrl: img8,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Kiran Das",
      Duration: "03 hr 00 mins",
      Lectures: 7,
      Level: "Intermediate",
      Language: "Hindi",
      Certificate: "Yes",
      Enrolled: 180,
    },
    {
      id: 9,
      imgUrl: img9,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Sneha Kapoor",
      Duration: "02 hr 20 mins",
      Lectures: 5,
      Level: "Beginner",
      Language: "English",
      Certificate: "No",
      Enrolled: 140,
    },
    {
      id: 10,
      imgUrl: img10,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Priya Nair",
      Duration: "04 hr 10 mins",
      Lectures: 9,
      Level: "Intermediate",
      Language: "English",
      Certificate: "Yes",
      Enrolled: 250,
    },
    {
      id: 11,
      imgUrl: img11,
      title: "Healthy salad",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Mohit Gupta",
      Duration: "03 hr 15 mins",
      Lectures: 8,
      Level: "Beginner",
      Language: "Hindi",
      Certificate: "No",
      Enrolled: 160,
    },
    {
      id: 12,
      imgUrl: img12,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
      Instructor: "Neha Reddy",
      Duration: "05 hr 00 mins",
      Lectures: 10,
      Level: "Advanced",
      Language: "English",
      Certificate: "Yes",
      Enrolled: 400,
    },
  ],
  FerturedFood: [
    {
      id: 1,
      imgUrl: img1,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
    {
      id: 2,
      imgUrl: img2,
      title: "Healthy salad",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "",
      qty: 1,
    },
    {
      id: 3,
      imgUrl: img3,
      title: "Soup and curry",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Certified Course",
      qty: 1,
    },
    {
      id: 4,
      imgUrl: img4,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
    {
      id: 5,
      imgUrl: img5,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
    {
      id: 6,
      imgUrl: img6,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
  ],
  freeReceips: [
    {
      id: 7,
      imgUrl: img7,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
    {
      id: 8,
      imgUrl: img8,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
    {
      id: 9,
      imgUrl: img9,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
  ],
  food: [
    {
      id: 10,
      imgUrl: img10,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
    {
      id: 11,
      imgUrl: img11,
      title: "Healthy salad",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
    {
      id: 12,
      imgUrl: img12,
      title: "All in one Pack",
      access: "Lifetime Access",
      ratings: "4.2",
      startCount: "4",
      ratingCounts: "2002",
      price: "5000",
      discountedPrice: "500",
      courseType: "Free Course",
      qty: 1,
    },
  ],
  postData: [
    {
      id: 1,
      imgUrl: post1,
      title: "Chef Cooking Life",
      time: "March 11, 2022 No Comments",
      description:
        "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident",
    },
    {
      id: 2,
      imgUrl: post2,
      title: "Cool way to cook food",
      time: "March 11, 2022 No Comments",
      description:
        "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident",
    },
    {
      id: 3,
      imgUrl: post3,
      title: "Make Spicy Food",
      time: "March 11, 2022 No Comments",
      description:
        "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident",
    },
  ],
};

const productSlice = createSlice({
  name: "products",
  initialState,
  reducers: {
    addToCart: (state, action) => {
      const product = state.products.find(
        (item) => item?.id === action.payload.id
      );
      if (product) {
        product.qty = action.payload.qty + 1;
      } else {
        state.products.push(action.payload);
      }
    },
    removeFromCart: (state, action) => {
      state.products = state.products.filter(
        (item) => item.id !== action.payload.id
      );
    },
    incrementItems: (state, action) => {
      const product = state.products.find(
        (item) => item.id === action.payload.id
      );
      if (product) {
        product.qty += 1;
      }
    },
    decrementFromCart: (state, action) => {
      const product = state.products.find(
        (item) => item.id === action.payload.id
      );
      if (product) {
        if (product.qty > 1) {
          product.qty -= 1;
        } else if (product.qty === 1) {
          state.products = state.products.filter(
            (item) => item.id !== action.payload.id
          );
        }
      }
    },
  },
});

export const { addToCart, removeFromCart, incrementItems, decrementFromCart } =
  productSlice.actions;

export default productSlice.reducer;
